### PR TITLE
IPython notebook on political dynasties

### PR DESCRIPTION
**Pull request by c4n**
- Count the presence of political families in 2019 general election

### CODE REVIEW

**Comment by heytitle** [comment]
Hi,

Thanks for the PR. It would be good if you could add an analysis section in README and introduce your notebook there.

**Comment by c4n** [comment]
Done. It might be better if the data also includes party-list MP candidates.

**Comment by c4n** [comment]
https://www.ect.go.th/ect_th/ewt_dl_link.php?nid=5085 เขาแสกนมาเบี้ยวๆแบบนี้จะดึงtextไงดีครับ55

**Comment by heytitle** [comment]
@c4n Do you have [Postman](https://www.getpostman.com)?

If yes, can you give me your email?  I can see you API endpoints that SmartVote consumes, one of the endpoint is for party list candidates.

**Comment by phoneee** [comment]
> https://www.ect.go.th/ect_th/ewt_dl_link.php?nid=5085 เขาแสกนมาเบี้ยวๆแบบนี้จะดึงtextไงดีครับ55

you can use tesseract, google vision api or abbyy finereader for thai text ocr

**Comment by c4n** [comment]
> @c4n Do you have [Postman](https://www.getpostman.com)?
> 
> If yes, can you give me your email? I can see you API endpoints that SmartVote consumes, one of the endpoint is for party list candidates.

I just signed up for Postman. email:udomc.cab@gmail.com



> > https://www.ect.go.th/ect_th/ewt_dl_link.php?nid=5085 เขาแสกนมาเบี้ยวๆแบบนี้จะดึงtextไงดีครับ55
> 
> you can use tesseract, google vision api or abbyy finereader for thai text ocr

Thanks for the suggestion. I will check it out if I need to extract something from PDFs. I think POSTMAN API would do the job, for now.

**Comment by heytitle** [comment]
@c4n it seems there is a typo in your your email address, `udomc.cab@gmail.com`. I can't send any email to you.

**Comment by c4n** [comment]
> @c4n it seems there is a typo in your your email address, `udomc.cab@gmail.com`. I can't send any email to you.

sorry!  
correction: udomc.can@gmail.com

**Comment by heytitle** [comment]
@c4n sent!

**Comment by c4n** [comment]
- Add a csv file for partylist candidates in /data directory

- Update ipython notebook

**Comment by heytitle** [comment]
thanks! Hope you enjoyed scraping the data 😄 .

**Comment by c4n** [comment]
> thanks! Hope you enjoyed scraping the data smile .

Iol. just found out that POSTMAN can generate python code which is neat.

**Comment by heytitle** [comment]
cool! thanks for the tip. I didn't know that.

**Comment by heytitle** [comment]
@c4n we're preparing a list of projects/articles that had been developed or written for the election. It would be great if you can write something regarding your political dynasties notebook. 

Feel free to discuss or open a PR at [1] if you're something. 

[1]: https://github.com/codeforthailand/awesome-election-62/issues/1#issuecomment-477028159

**Pull request merged**
